import { Menu } from "@/components/brand/dashboard/Menu";
import { SidebarMobile } from "@/components/brand/dashboard/MobileSidebar";
import { UserNav } from "@/components/brand/dashboard/UserNav";
import ModeToggle from "@/components/ModeToggle";
import { ScrollArea } from "@/components/ui/scroll-area";
import ProtectedRoute from "@/provider/protectedProvider";
import RoleCheckProvider from "@/provider/roleCheckProvider";
import Link from "next/link";

export const metadata = {
  title: "Learning Platform- DiagnoTech-Ai",
  description: "Generated by create next app",
};

export default function DashboardLayout({ children }: { children: React.ReactNode }) {
  return (
    <ProtectedRoute>
      <RoleCheckProvider>
        <section className="w-full h-screen flex flex-col">
          <div className="flex flex-1 overflow-hidden">
            <div className="hidden lg:flex flex-col w-[220px] lg:w-[280px] border-r bg-muted/40">
              <div className="flex h-14 items-center border-b px-4 lg:h-[60px] lg:px-6">
                <Link
                  href="/"
                  className="flex items-center gap-2 font-semibold"
                >
                  <img
                    src="/assets/logo_final.png"
                    className="w-10 duration-500 cursor-pointer"
                    alt="Logo"
                  />
                  <span>DiagnoTech-Ai</span>
                </Link>
              </div>

              <Menu />
            </div>
            <div className="flex-1 flex flex-col overflow-hidden">
              <header className="border-b flex gap-4 h-14 items-center justify-end lg:h-[60px] px-4 lg:px-6">
                <SidebarMobile />
                <ModeToggle />
                <UserNav />
              </header>
              <main className="flex-1 overflow-auto">
                <ScrollArea className="h-full">{children}</ScrollArea>
              </main>
            </div>
          </div>
        </section>
      </RoleCheckProvider>
    </ProtectedRoute>
  );
}
